version: "3.9"

services:
  postgres:
    container_name: postgres-db-dev
    image: postgres:15
    env_file: .env
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: django-dev
    environment:
      - "DJANGO_DEBUG=true"
    command: ["/backend/docker-cmd.sh", "--debug"]
    volumes:
      - "media-data:/var/www/media" 
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
  postgres-data:
  media-data:
